version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: youtdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: my_db_password
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - app-network
    restart: unless-stopped

  server:
    build: ./server
    ports:
      - "5000:5000"
    depends_on:
      - mariadb
    environment:
      MARIA_HOST: mariadb
      MARIA_DATABASE: youtdb
      MARIA_USER: admin
      MARIA_PASSWORD: my_db_password
      JWT_SECRET: super_secret_jwt_key
      FRONTEND_ORIGIN: http://ec2-3-107-19-197.ap-southeast-2.compute.amazonaws.com:8080
    networks:
      - app-network
    restart: unless-stopped

  webclient:
    build: ./webclient
    ports:
      - "8080:8080"
    command: npm run dev -- --host 0.0.0.0 --port 8080
    depends_on:
      - server
    networks:
      - app-network
    volumes:
      - ./config.json:/app/config.json:ro

    restart: unless-stopped

volumes:
  mariadb_data:

networks:
  app-network:
