FROM node:20-slim
WORKDIR /usr/src/app

# Install FFmpeg
RUN apt-get update && \
    apt-get install -y ffmpeg && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY package*.json ./
RUN npm install
# RUN npm install aws-sdk

COPY . .

CMD ["node", "worker.js"]
