version: "3.9"

services:
  app:
    build: .
    container_name: server-app-1  
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/src/app         # Mount your project folder
      - /usr/src/app/node_modules # Keep container node_modules separate
    environment:
      - NODE_ENV=development
